Level 3 Introduction to Form element
pupilfirst/web-development-101-script pull request #11
Opened 2022-05-30 18:09 UTC by vikispeaks

2022-05-31 17:30 UTC, mjzac requested changes

2022-05-31 17:30 UTC, mjzac commented on basic-introduction-html-css/introduction-to-form-element/README.md
> +In this video, we will learn about HTML Form element and how it is used to collect User input in web pages.
~~User~~ user

2022-06-08 08:56 UTC, vikispeaks commented
@mjzac Not including action and method for this as this is still an introduction lesson. Will probably move this out after discussions to the later chapter.

2022-06-08 09:07 UTC, mjzac approved these changes
Looks good to me.

2022-06-08 09:07 UTC, merged