V2 avishek js add update delete objects
pupilfirst/web-development-101-script pull request #15
Opened 2022-06-06 11:25 UTC by avishekjana

2022-06-07 09:34 UTC, mjzac requested changes

2022-06-07 09:34 UTC, mjzac commented on numbers-booleans-objects/add-update-delete-objects/README.md
> +And in this lesson, we will learn to add, update and delete properties of an Javascript Object.
```suggestion
And in this lesson, we will learn to add, update and delete properties of a JavaScript Object.
```

2022-06-07 09:34 UTC, mjzac commented on numbers-booleans-objects/add-update-delete-objects/README.md
> +Assume that you've a a *employee* object that already exists. One way is to add a property to this  *employee* object is, by using the **dot notation**:
```suggestion
Assume that you've an *employee* object that already exists. One way to add a property to this  *employee* object is, by using the **dot notation**:
```

2022-06-07 09:34 UTC, mjzac commented on numbers-booleans-objects/add-update-delete-objects/README.md
> +It does the same thing as the previous example, but we can have invalid property identifiers in the string.
```suggestion
It does the same thing as the previous example, but we can have property identifiers with hyphen or space with this notation.
```

2022-06-07 09:34 UTC, mjzac commented on numbers-booleans-objects/add-update-delete-objects/README.md
> +This `delete` keyword deletes both the value of the property and the property itself. And, after deletion, the property cannot be used.
```suggestion
This `delete` keyword deletes both the value of the property and the property itself. And, after deletion, accessing the property will return `undefined`.
```

2022-06-08 04:07 UTC, avishekjana commented on numbers-booleans-objects/add-update-delete-objects/README.md
> +This `delete` keyword deletes both the value of the property and the property itself. And, after deletion, the property cannot be used.
Resolved

2022-06-08 04:07 UTC, avishekjana commented on numbers-booleans-objects/add-update-delete-objects/README.md
> +It does the same thing as the previous example, but we can have invalid property identifiers in the string.
Resolved

2022-06-08 04:07 UTC, avishekjana commented on numbers-booleans-objects/add-update-delete-objects/README.md
> +Assume that you've a a *employee* object that already exists. One way is to add a property to this  *employee* object is, by using the **dot notation**:
Resolved

2022-06-08 04:08 UTC, merged