Creating object script added
pupilfirst/web-development-101-script pull request #16
Opened 2022-06-06 11:30 UTC by avishekjana

2022-06-07 09:28 UTC, mjzac requested changes

2022-06-07 09:28 UTC, mjzac commented on numbers-booleans-objects/creating-and-working-with-objects/README.md
> +In Javascript, an object is something which is very powerful, and you are going to work with them all the time. So, let's get started.
```suggestion
In JavaScript, an object is a powerful construct, and you are going to work with them all the time. So, let's get started.
```

2022-06-08 00:54 UTC, avishekjana commented on numbers-booleans-objects/creating-and-working-with-objects/README.md
> +A Javascript object is a collection of named values. Like many other programming languages, it can be compared to objects in real life. Compare it with a cup, for example. A cup is an object, with pr
Resolved.

2022-06-08 00:54 UTC, avishekjana commented on numbers-booleans-objects/creating-and-working-with-objects/README.md
> +In Javascript, an object is something which is very powerful, and you are going to work with them all the time. So, let's get started.
Resolved.

2022-06-08 00:54 UTC, avishekjana commented on numbers-booleans-objects/creating-and-working-with-objects/README.md
> +In this lesson, we will learn about Javascript Objects.
Resolved.

2022-06-08 00:55 UTC, merged